### PR TITLE
Enable 6.2 specific tests

### PR DESCRIPTION
**Pull request by mijicd**
This pull request enables ignored tests as they were pending 6.2 docker image release.

### CODE REVIEW

**Comment by mijicd** [comment]
cc @anovakovic01 it looks like something's off with these tests :)

**Comment by anovakovic01** [comment]
> cc @anovakovic01 it looks like something's off with these tests :)

I'll look into it.

**Comment by anovakovic01** [comment]
@mijicd Fixed.

**Review by anovakovic01 — APPROVED** [review]
LGTM!

**Pull request merged**
