### PR TITLE
Implement keys API in test executor (#194)

### PR DESCRIPTION
**Pull request by rfmejia**
This draft PR implements test executors for keys (#194) in two parts. Please comment on the approach if you have any concerns/improvements:

### Key Management
All keys are tracked in `keys: TSet[String]`. Support for key-related commands are performed against this set. To modify an underlying data structure, Redis commands must use functions that also manage adding keys and expirations (e.g., `def putList = list.put(...) <* keys.put(...) <* expirations.delete(...)`).

### Expiration Management
We introduce the concept of time whenever a Redis command is executed. First, keys are mapped to its expiration Instant (i.e., *when* it expires) in `expirations: TMap[String, Instant]`. Mappings are added using EXPIRE, EXPIREAT, etc. Mappings are removed using PERSIST or any command that modifies an existing key.

When a command is executed, the current time is captured from `zio.clock.Clock`. All keys in `expirations` with an instant before the current time are purged. Finally, execute the Redis command as usual using put and delete functions.

#### Action items
Implement the rest of commands in the keys test suite. Also implement commands in other test suites that use expirations (e.g., PSETEX). Finally, figure out how to use `zio.test.environment.TestClock` for reliable testing of expirations.

### CODE REVIEW

**Comment by rfmejia** [comment]
Also since the fundamental structure of test executors are being modified in this PR, I will wait until other ongoing work in test executors are merged in (#363, #370) .

**Comment by anatolysergeev** [comment]
Hello @rfmejia . Your PR have not been finished and updated for 6 months(( Don't you mind if i have a try to continue your work?

**Comment by rfmejia** [comment]
@anatolysergeev Yes please do, I have been swamped. I am optimistic about the current approach which adds `TestClock` to the executor and domain tests in order to facilitate TTL checking, and most of the tests were already updated. But I'm afraid the draft has diverged far from the main branch, so it might  be best to start over. Thanks.

**Comment by mijicd** [comment]
Closed in #480

**Pull request closed without merging**
