### PR TITLE
ApiSpec tests for HyperLogLog

### LINKED ISSUE #61: Test HyperLogLog API
Expand the [ApiSpec](https://github.com/zio/zio-redis/blob/master/src/test/scala/zio/redis/ApiSpec.scala) with HLL commands.

### PR DESCRIPTION
**Pull request by geoffjohn11**
Closes #61

### CODE REVIEW

**Comment by mijicd** [comment]
@geoffjohn11 Please rebase, and pull out the tests in a separate trait as introduced by #83. Looks good generally!  :)

**Comment by mijicd** [comment]
@geoffjohn11 why closing it though?

**Comment by geoffjohn11** [comment]
@mijicd Should I reopen?  Sorry if I've made a mess by opening 2 branches.

**Comment by mijicd** [comment]
@geoffjohn11 yeah, feel free to sync on this one and continue. If it is easier for you I don't mind if you want to continue on another one and open a separate PR, was just surprised why you closed it :).

**Pull request closed without merging**
