### PR TITLE
Update Sets API documentation with standard naming

### PR DESCRIPTION
**Pull request by justinhj**
This updates the naming of parameters where there is a first item and a list of further items. Based on recommendation by @anovakovic01 in PR #183

### CODE REVIEW

**Comment by justinhj** [comment]
fixes #177

**Review by anovakovic01 — CHANGES_REQUESTED** [review]
As @mijicd suggested, we decided to update scaladoc format so that it contains an empty line as a first line, so while you're at it, can you fix that as well?

**Comment by justinhj** [comment]
`  /** Add one or more members to a set
   *
   * @param key Key of set to add to`

Not sure what you mean. Could you reformat this example in the desired format?

Also I notice that the scala format command is

**Comment by mijicd** [comment]
@justinhj He meant:

```
/**
 * Add one or more ...
 */
```

**Comment by anovakovic01** [comment]
> ```
>  /** Add one or more members to a set
>    *
>    * @param key Key of set to add to
> ```
> 
> Not sure what you mean. Could you reformat this example in the desired format?

Sure:
```
/** 
 *  Add one or more members to a set
 *
 *  @param key Key of set to add to
```

**Comment by justinhj** [comment]
ok sure, I prefer that myself

**Review by mijicd — APPROVED** [review]

**Review by anovakovic01 — APPROVED** [review]

**Pull request merged**
